### ISSUE TITLE
question

### ISSUE THREAD

**Issue by hos-sein** [rahimaee/smsir#1]
سلام وقت بخير
تو كد زير به جاي سكرت كي بايد چي بذاريم و از كجا ميشه گرفتش؟
get_token(UserApiKey='', SecretKey='')

**Comment by rahimaee** [comment]
سلام وقت بخیر 
اول وارد حساب کاربری خود درسایت sms.ir میشد
درسمت راست قسمت داشبورد  دسته  بندی برنامه نویسان و گزینه کلید وب سرویس  انتخاب میکند
و یک Security code به نام  دلخواه ایجاد میکند و بعد برای شما یک UserApiKey بصورت خود کارساخته میشود
درعکس برای شما مشخص کردم
![is1](https://user-images.githubusercontent.com/19734912/194790462-95f469c1-292d-47f8-8142-307d3c041247.PNG)

در اخر ممنون میشم بهم استار بدین وفالو کنید
